apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads-tenant-maint
  namespace: argocd
spec:
  description: maint tenant
  sourceRepos:
  - '*'
  destinations:
  - server: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
