apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads-tenant-edu
  namespace: argocd
spec:
  description: edu tenant
  sourceRepos:
  - '*'
  destinations:
  - server: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
