apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-appset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laceth/multitenant.git
    targetRevision: HEAD
    path: argocd/appsets/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
