apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx-all-clusters
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - { name: use1 }
      - { name: usw2 }
      - { name: usc1 }
      - { name: use2 }
  template:
    metadata:
      name: ingress-nginx-{{name}}
    spec:
      project: default
      destination:
        name: "{{name}}"
        namespace: ingress-nginx
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.11.0   # if this exact version 404s, bump to the latest
        helm:
          releaseName: ingress-nginx
          values: |
            controller:
              service:
                type: LoadBalancer      # works with MetalLB
              metrics:
                enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

